modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"
issueTrackerURL="https://github.com/sudolev/DynamicVillageMod/issues" #optional

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
displayURL="https://sudolev.github.io/DynamicVillageMod/" #optional
logoFile="icon.png" #optional
credits="Ben001109, Fatasiangamer" #optional
authors="${mod_authors}" #optional
description='''
${mod_description}
'''

[[dependencies.${mod_id}]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${forge_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="create"
    mandatory=true
    versionRange="[6.0.0,)"
    ordering="AFTER"
    side="BOTH"
